language: go

go:
  - 1.11
  - 1.12
  - tip

env:
  - GO111MODULE=on
  - COVERALLS_TOKEN=7x2c0Eo565r4PQfUIkms12XZRYTXyaCTm

matrix:
  fast_finish: true

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go vet -x ./...
  - go test -v -race ./...
  - ./coveralls.bash
