
language: go

go:
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - 1.10
  - 1.11
  - 1.12
  - tip

matrix:
  fast_finish: true

script:
  - go vet -x ./...
  - go test -v -race ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)